server:
  port: 12345

logging:
  charset:
    console: UTF-8
    file: UTF-8

spring:
  profiles:
    active: h2
  batch:
    job.enabled: false # false: 앱 구동시 job 실행 안 함
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        query.in_clause_parameter_padding: true

---

spring:
  config:
    activate:
      on-profile: mysql
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: mysql


---

spring:
  config:
    activate:
      on-profile: h2
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:
